set(CMAKE_DLLTOOL "${CMAKE_CURRENT_LIST_DIR}/zig-dlltool.cmd")
set(CMAKE_AR "${CMAKE_CURRENT_LIST_DIR}/zig-ar.cmd")
set(CMAKE_OBJCOPY "${CMAKE_CURRENT_LIST_DIR}/zig-objcopy.cmd")
set(CMAKE_RANLIB "${CMAKE_CURRENT_LIST_DIR}/zig-ranlib.cmd")
set(CMAKE_LINKER "${CMAKE_CURRENT_LIST_DIR}/zig-lib.cmd")
set(CMAKE_RC_COMPILER "${CMAKE_CURRENT_LIST_DIR}/zig-rc.cmd")

set(CMAKE_C_COMPILER "${CMAKE_CURRENT_LIST_DIR}/zig-cc.cmd")
set(CMAKE_C_COMPILER_AR "${CMAKE_CURRENT_LIST_DIR}/zig-ar.cmd")
set(CMAKE_C_COMPILER_RANLIB "${CMAKE_CURRENT_LIST_DIR}/zig-ranlib.cmd")

set(CMAKE_CXX_COMPILER "${CMAKE_CURRENT_LIST_DIR}/zig-cxx.cmd")
set(CMAKE_CXX_COMPILER_AR "${CMAKE_CURRENT_LIST_DIR}/zig-ar.cmd")
set(CMAKE_CXX_COMPILER_RANLIB "${CMAKE_CURRENT_LIST_DIR}/zig-ranlib.cmd")

set(CMAKE_ASM_COMPILER "${CMAKE_CURRENT_LIST_DIR}/zig-cc.cmd")
set(CMAKE_ASM_COMPILER_AR "${CMAKE_CURRENT_LIST_DIR}/zig-ar.cmd")
set(CMAKE_ASM_COMPILER_RANLIB "${CMAKE_CURRENT_LIST_DIR}/zig-ranlib.cmd")